name: Test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: yarn install --frozen-lockfile
      - run: yarn lint && yarn test
